export const VISION_URL = "https://vision.googleapis.com/v1/images:annotate?key="
export const FLAG_API_URL = "https://countryflagsapi.com/svg/"
export const TRANSLATE_URL = "https://translation.googleapis.com/language/translate/v2?key="
export const DICTIONARY_URL = "https://api.dictionaryapi.dev/api/v2/entries/en/"
export const CURRENT_VERSION = "2.1.0"
export const TEXT_TO_SPEECH_URL = "https://texttospeech.googleapis.com/v1beta1/text:synthesize?key="
export const TEXT_TO_SPEECH_VOICE_LIST_URL = "https://texttospeech.googleapis.com/v1beta1/voices?key="
